### ISSUE TITLE
getting error while loading pretrained model

### ISSUE THREAD

**Issue by Alizah-Masood** [zkl20061823/JTFN#1]
I'm unable to load the pretrained model file that you have provided. Can you please check if the file is correctly uploaded or not?
I'm getting the following error while loading the model:

[enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

will look forward to your response. Thanks.

**Comment by MingfeiCheng** [comment]
Thanks for your reminder. We will check it and update soon.

**Comment by MingfeiCheng** [comment]
We have updated our repo. The pretrained model file can be loaded correctly. You can check the latest version :).

**Comment by Alizah-Masood** [comment]
Thanks a lot for updating the files. But the link provided for pretrained model files is not working for me, perhaps it does not work in my region. Can you please upload that file on google drive also?

**Comment by zkl20061823** [comment]
please check the newly updated google cloud.
